### ISSUE TITLE
geoshape-config updateip, requires a restart

### ISSUE THREAD

**Issue by smesdaghi** [ROGUE-JCTD/rpmbuild#3]
without a restart, the old  GEOSERVER_URL value from local settings is passed into maploom which promps the user input when maploom is launched. restart fixed issue. Low priority.

**Comment by BerryDaniel** [comment]
branch 1.7 fixes this issue

https://github.com/ROGUE-JCTD/rpmbuild/blob/1.7/SOURCES/geoshape-config#L271
