### ISSUE TITLE
Littlecms dependency fails on RHEL

### ISSUE THREAD

**Issue by garnertb** [ROGUE-JCTD/rpmbuild#9]
yum search lcms
Loaded plugins: product-id, security, subscription-manager
================================================= N/S Matched: lcms ==================================================
lcms-libs.i686 : Library for lcms
lcms-libs.x86_64 : Library for lcms
lcms2-utils.x86_64 : Utility applications for lcms2
lcms2.i686 : Color Management Engine
lcms2.x86_64 : Color Management Engine
lcms2-devel.i686 : Development files for LittleCMS
lcms2-devel.x86_64 : Development files for LittleCMS

yum search littlecms
Loaded plugins: product-id, security, subscription-manager
=============================================== N/S Matched: littlecms ===============================================
lcms2-devel.i686 : Development files for LittleCMS
lcms2-devel.x86_64 : Development files for LittleCMS

After I installed lcms2-devel.x86_64 and lcms2.x86_64 I get: 

Error: Package: geoshape-1.7.11-2.el6.x86_64 (geoshape)
           Requires: littlecms

**Comment by garnertb** [comment]
Workaround: 

```wget http://mirror.cogentco.com/pub/linux/centos/6.7/os/x86_64//Packages/lcms-1.19-1.el6.x86_64.rpm && rpm -Uvh lcms-1.19-1.el6.x86_64.rpm```

**Comment by BerryDaniel** [comment]
Adjusted geoshape.spec now with lcms2-devel - https://github.com/ROGUE-JCTD/rpmbuild/blob/master/SPECS/geoshape.spec#L58 

lcms2 is now being built locally and will be added to the repo shortly. When the next version is done for MapLoom we can update geoshape with this fix.. cool?
